### PR TITLE
The attachment upload api expects a document

### PR DESCRIPTION
**Pull request by jamesmacwilliam**
- this was causing an invalid document error when uploading

### CODE REVIEW

**Comment by jamesmacwilliam** [comment]
cc @spreemo/code-reviewers

**Comment by whylom** [comment]
If this actually fixes the bug, this is pretty uncontroversial. 👍

**Comment by sharabromberg** [comment]
@jamesmacwilliam can we close the associated ticket? 
@ivanoblomov can you merge master into your branch, then redeploy to production-standby? we need this fix for phase 2 testing

**Comment by sharabromberg** [comment]
@jamesmacwilliam @ivanoblomov James beat me to it lol, ignore the merge/redeploy request since it has already been done

**Pull request merged**
